<?php

return function (): array {
    if (! app()->environment('local', 'testing')) {
        return [
            'metrics' => [
                'total_transactions' => 0,
                'total_sales' => 0,
                'average_transaction' => 0,
                'top_payment_method' => '-',
                'top_payment_percentage' => 0,
            ],
            'outlets' => [],
            'transactions' => [],
        ];
    }

    return [
        'metrics' => [
            'total_transactions' => 382,
            'total_sales' => 14850000,
            'average_transaction' => 38874,
            'top_payment_method' => 'QRIS',
            'top_payment_percentage' => 58,
        ],
        'outlets' => [
            'Outlet Sudirman',
            'Outlet Senopati',
            'Outlet BSD',
        ],
        'transactions' => [
            [
                'id' => 1,
                'transaction_number' => 'TRX-260921-001',
                'sold_at' => '21 Sep 2026 · 09:42',
                'sold_at_raw' => '2026-09-21 09:42',
                'outlet_name' => 'Outlet Sudirman',
                'shift_name' => 'Shift Pagi (08:00 - 16:00)',
                'customer_name' => 'Andi',
                'payment_method' => 'QRIS',
                'payment_status' => 'Lunas',
                'status' => 'Selesai',
                'subtotal' => 85000,
                'discount_amount' => 0,
                'tax_amount' => 0,
                'total_amount' => 85000,
                'paid_at' => '21 Sep 2026 · 09:42',
                'cash_received' => null,
                'change_amount' => null,
                'gross_profit' => 38500,
                'note' => 'Less sugar untuk latte',
                'order_status' => null,
                'estimated_completed_at' => null,
                'items' => [
                    [
                        'product_name' => 'Kopi Susu Gula Aren',
                        'product_sku' => 'KOPI-001',
                        'unit_price' => 25000,
                        'quantity' => '2',
                        'unit' => 'cup',
                        'kind' => 'product',
                        'pricing_unit' => 'per_unit',
                        'line_total' => 50000,
                    ],
                    [
                        'product_name' => 'Croissant Almond',
                        'product_sku' => 'PAS-003',
                        'unit_price' => 35000,
                        'quantity' => '1',
                        'unit' => 'pcs',
                        'kind' => 'product',
                        'pricing_unit' => 'per_unit',
                        'line_total' => 35000,
                    ],
                ],
            ],
            [
                'id' => 2,
                'transaction_number' => 'TRX-260921-002',
                'sold_at' => '21 Sep 2026 · 10:15',
                'sold_at_raw' => '2026-09-21 10:15',
                'outlet_name' => 'Outlet Sudirman',
                'shift_name' => 'Shift Pagi (08:00 - 16:00)',
                'customer_name' => null,
                'payment_method' => 'Tunai',
                'payment_status' => 'Lunas',
                'status' => 'Selesai',
                'subtotal' => 45000,
                'discount_amount' => 5000,
                'tax_amount' => 4000,
                'total_amount' => 44000,
                'paid_at' => '21 Sep 2026 · 10:15',
                'cash_received' => 50000,
                'change_amount' => 6000,
                'gross_profit' => 21000,
                'note' => null,
                'order_status' => null,
                'estimated_completed_at' => null,
                'items' => [
                    [
                        'product_name' => 'Americano Dingin',
                        'product_sku' => 'KOPI-002',
                        'unit_price' => 22000,
                        'quantity' => '1',
                        'unit' => 'cup',
                        'kind' => 'product',
                        'pricing_unit' => 'per_unit',
                        'line_total' => 22000,
                    ],
                    [
                        'product_name' => 'Cinnamon Roll',
                        'product_sku' => 'PAS-001',
                        'unit_price' => 23000,
                        'quantity' => '1',
                        'unit' => 'pcs',
                        'kind' => 'product',
                        'pricing_unit' => 'per_unit',
                        'line_total' => 23000,
                    ],
                ],
            ],
            [
                'id' => 3,
                'transaction_number' => 'TRX-260921-003',
                'sold_at' => '21 Sep 2026 · 11:05',
                'sold_at_raw' => '2026-09-21 11:05',
                'outlet_name' => 'Outlet Senopati',
                'shift_name' => 'Shift Pagi (08:00 - 16:00)',
                'customer_name' => 'Budi Santoso',
                'payment_method' => 'Transfer',
                'payment_status' => 'Belum Lunas',
                'status' => 'Dibatalkan',
                'subtotal' => 120000,
                'discount_amount' => 0,
                'tax_amount' => 0,
                'total_amount' => 120000,
                'paid_at' => null,
                'cash_received' => null,
                'change_amount' => null,
                'gross_profit' => 0,
                'note' => 'Pembeli membatalkan pesanan sebelum disiapkan',
                'order_status' => null,
                'estimated_completed_at' => null,
                'items' => [
                    [
                        'product_name' => 'Paket Brunch Spesial',
                        'product_sku' => 'SET-001',
                        'unit_price' => 60000,
                        'quantity' => '2',
                        'unit' => 'porsi',
                        'kind' => 'product',
                        'pricing_unit' => 'per_unit',
                        'line_total' => 120000,
                    ],
                ],
            ],
            [
                'id' => 4,
                'transaction_number' => 'TRX-260921-004',
                'sold_at' => '21 Sep 2026 · 11:30',
                'sold_at_raw' => '2026-09-21 11:30',
                'outlet_name' => 'Outlet BSD',
                'shift_name' => 'Shift Pagi (08:00 - 16:00)',
                'customer_name' => 'Siti Rahma',
                'payment_method' => 'QRIS',
                'payment_status' => 'Lunas',
                'status' => 'Selesai',
                'subtotal' => 34000,
                'discount_amount' => 0,
                'tax_amount' => 0,
                'total_amount' => 34000,
                'paid_at' => '21 Sep 2026 · 11:30',
                'cash_received' => null,
                'change_amount' => null,
                'gross_profit' => 17000,
                'note' => 'Pewangi lavender aroma lembut',
                'order_status' => 'Diproses',
                'estimated_completed_at' => '22 Sep 2026 · 14:00',
                'items' => [
                    [
                        'product_name' => 'Laundry Kiloan',
                        'product_sku' => 'LND-001',
                        'unit_price' => 8000,
                        'quantity' => '4.250',
                        'unit' => 'kg',
                        'kind' => 'service',
                        'pricing_unit' => 'per_kg',
                        'line_total' => 34000,
                    ],
                ],
            ],
            [
                'id' => 5,
                'transaction_number' => 'TRX-260921-005',
                'sold_at' => '21 Sep 2026 · 12:10',
                'sold_at_raw' => '2026-09-21 12:10',
                'outlet_name' => 'Outlet Sudirman',
                'shift_name' => 'Shift Siang (12:00 - 20:00)',
                'customer_name' => 'Diana Pratiwi',
                'payment_method' => 'Kartu',
                'payment_status' => 'Lunas',
                'status' => 'Selesai',
                'subtotal' => 135000,
                'discount_amount' => 15000,
                'tax_amount' => 12000,
                'total_amount' => 132000,
                'paid_at' => '21 Sep 2026 · 12:10',
                'cash_received' => null,
                'change_amount' => null,
                'gross_profit' => 62000,
                'note' => null,
                'order_status' => null,
                'estimated_completed_at' => null,
                'items' => [
                    [
                        'product_name' => 'Caramel Macchiato',
                        'product_sku' => 'KOPI-005',
                        'unit_price' => 38000,
                        'quantity' => '2',
                        'unit' => 'cup',
                        'kind' => 'product',
                        'pricing_unit' => 'per_unit',
                        'line_total' => 76000,
                    ],
                    [
                        'product_name' => 'Pasta Carbonara',
                        'product_sku' => 'FOD-002',
                        'unit_price' => 59000,
                        'quantity' => '1',
                        'unit' => 'porsi',
                        'kind' => 'product',
                        'pricing_unit' => 'per_unit',
                        'line_total' => 59000,
                    ],
                ],
            ],
        ],
    ];
};
