<?php

return function (): array {
    if (! app()->environment('local', 'testing')) {
        return [
            'summary' => [
                'cash_in' => 0,
                'cash_out' => 0,
                'net_cash_flow' => 0,
                'total_expense' => 0,
            ],
            'categories' => [],
            'outlets' => [],
            'ledgers' => [],
            'expenses' => [],
        ];
    }

    $ledgers = [
        [
            'id' => 1,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => 1,
            'type' => 'in',
            'amount' => 125000,
            'category' => 'sale',
            'category_label' => 'Penjualan',
            'note' => 'Penjualan tunai kasir pagi',
            'reference_id' => 'TRX-260921-001',
            'sale_sync_id' => 'SYNC-SALE-001',
            'occurred_at_raw' => '2026-09-21 10:15:00',
            'occurred_at' => '21 Sep 2026 · 10:15',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => 'SHIFT-001',
        ],
        [
            'id' => 2,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => 1,
            'type' => 'out',
            'amount' => 75000,
            'category' => 'operational',
            'category_label' => 'Operasional',
            'note' => 'Beli es batu kristal 3 kantong',
            'reference_id' => 'EXP-260921-001',
            'sale_sync_id' => null,
            'occurred_at_raw' => '2026-09-21 08:30:00',
            'occurred_at' => '21 Sep 2026 · 08:30',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => 'SHIFT-001',
        ],
        [
            'id' => 3,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => 1,
            'type' => 'in',
            'amount' => 350000,
            'category' => 'sale',
            'category_label' => 'Penjualan',
            'note' => 'Penjualan paket coffee break kantor',
            'reference_id' => 'TRX-260921-002',
            'sale_sync_id' => 'SYNC-SALE-002',
            'occurred_at_raw' => '2026-09-21 11:45:00',
            'occurred_at' => '21 Sep 2026 · 11:45',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => 'SHIFT-001',
        ],
        [
            'id' => 4,
            'business_id' => 1,
            'outlet_id' => 2,
            'shift_id' => 2,
            'type' => 'in',
            'amount' => 210000,
            'category' => 'sale',
            'category_label' => 'Penjualan',
            'note' => 'Penjualan minuman dine-in',
            'reference_id' => 'TRX-260920-003',
            'sale_sync_id' => 'SYNC-SALE-003',
            'occurred_at_raw' => '2026-09-20 15:20:00',
            'occurred_at' => '20 Sep 2026 · 15:20',
            'outlet_name' => 'Outlet Cabang Barat',
            'shift_number' => 'SHIFT-002',
        ],
        [
            'id' => 5,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => 1,
            'type' => 'out',
            'amount' => 50000,
            'category' => 'other',
            'category_label' => 'Lainnya',
            'note' => 'Transportasi pengantaran pesanan',
            'reference_id' => null,
            'sale_sync_id' => null,
            'occurred_at_raw' => '2026-09-20 13:10:00',
            'occurred_at' => '20 Sep 2026 · 13:10',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => 'SHIFT-001',
        ],
        [
            'id' => 6,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => null,
            'type' => 'in',
            'amount' => 500000,
            'category' => 'cash_in',
            'category_label' => 'Setoran Kas',
            'note' => 'Tambahan modal kembalian laci',
            'reference_id' => 'ADJ-260919-001',
            'sale_sync_id' => null,
            'occurred_at_raw' => '2026-09-19 09:00:00',
            'occurred_at' => '19 Sep 2026 · 09:00',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => null,
        ],
        [
            'id' => 7,
            'business_id' => 1,
            'outlet_id' => 2,
            'shift_id' => 3,
            'type' => 'out',
            'amount' => 120000,
            'category' => 'operational',
            'category_label' => 'Operasional',
            'note' => 'Bahan pembersih mesin kopi dan lap microfiber',
            'reference_id' => 'EXP-260918-001',
            'sale_sync_id' => null,
            'occurred_at_raw' => '2026-09-18 16:30:00',
            'occurred_at' => '18 Sep 2026 · 16:30',
            'outlet_name' => 'Outlet Cabang Barat',
            'shift_number' => 'SHIFT-003',
        ],
        [
            'id' => 8,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => 1,
            'type' => 'in',
            'amount' => 450000,
            'category' => 'sale',
            'category_label' => 'Penjualan',
            'note' => 'Penjualan weekend event',
            'reference_id' => 'TRX-260917-001',
            'sale_sync_id' => 'SYNC-SALE-004',
            'occurred_at_raw' => '2026-09-17 14:00:00',
            'occurred_at' => '17 Sep 2026 · 14:00',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => 'SHIFT-001',
        ],
        [
            'id' => 9,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => null,
            'type' => 'out',
            'amount' => 250000,
            'category' => 'operational',
            'category_label' => 'Operasional',
            'note' => 'Isi ulang galon air mineral & gas elpiji',
            'reference_id' => 'EXP-260916-001',
            'sale_sync_id' => null,
            'occurred_at_raw' => '2026-09-16 11:00:00',
            'occurred_at' => '16 Sep 2026 · 11:00',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => null,
        ],
        [
            'id' => 10,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => 1,
            'type' => 'in',
            'amount' => 290000,
            'category' => 'sale',
            'category_label' => 'Penjualan',
            'note' => 'Penjualan pastry dan minuman',
            'reference_id' => 'TRX-260915-001',
            'sale_sync_id' => 'SYNC-SALE-005',
            'occurred_at_raw' => '2026-09-15 10:30:00',
            'occurred_at' => '15 Sep 2026 · 10:30',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => 'SHIFT-001',
        ],
    ];

    $expenses = [
        [
            'id' => 1,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => 1,
            'description' => 'Pembelian Es Batu Kristal',
            'category' => 'Operasional',
            'amount' => 75000,
            'status' => 'recorded',
            'occurred_at_raw' => '2026-09-21 08:20:00',
            'occurred_at' => '21 Sep 2026 · 08:20',
            'notes' => 'Kebutuhan operasional minuman harian',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => 'SHIFT-001',
        ],
        [
            'id' => 2,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => 1,
            'description' => 'Ongkir Pengantaran Kopi Pelanggan',
            'category' => 'Transportasi',
            'amount' => 50000,
            'status' => 'recorded',
            'occurred_at_raw' => '2026-09-20 13:10:00',
            'occurred_at' => '20 Sep 2026 · 13:10',
            'notes' => 'Kurir instan order corporate',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => 'SHIFT-001',
        ],
        [
            'id' => 3,
            'business_id' => 1,
            'outlet_id' => 2,
            'shift_id' => 3,
            'description' => 'Sabun Cuci Piring & Microfiber',
            'category' => 'Kebersihan',
            'amount' => 120000,
            'status' => 'recorded',
            'occurred_at_raw' => '2026-09-18 16:30:00',
            'occurred_at' => '18 Sep 2026 · 16:30',
            'notes' => 'Perlengkapan sanitasi bar cafe',
            'outlet_name' => 'Outlet Cabang Barat',
            'shift_number' => 'SHIFT-003',
        ],
        [
            'id' => 4,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => null,
            'description' => 'Isi Ulang 5 Galon & Tabung Gas',
            'category' => 'Bahan Baku',
            'amount' => 250000,
            'status' => 'recorded',
            'occurred_at_raw' => '2026-09-16 11:00:00',
            'occurred_at' => '16 Sep 2026 · 11:00',
            'notes' => null,
            'outlet_name' => 'Outlet Utama',
            'shift_number' => null,
        ],
        [
            'id' => 5,
            'business_id' => 1,
            'outlet_id' => 1,
            'shift_id' => 1,
            'description' => 'Paper Cup 16oz & Sedotan Kertas',
            'category' => 'Perlengkapan',
            'amount' => 180000,
            'status' => 'recorded',
            'occurred_at_raw' => '2026-09-15 14:20:00',
            'occurred_at' => '15 Sep 2026 · 14:20',
            'notes' => 'Stok kemasan takeaway tambahan',
            'outlet_name' => 'Outlet Utama',
            'shift_number' => 'SHIFT-001',
        ],
    ];

    $cashIn = 0;
    $cashOut = 0;
    foreach ($ledgers as $l) {
        if ($l['type'] === 'in') {
            $cashIn += (int) $l['amount'];
        } elseif ($l['type'] === 'out') {
            $cashOut += (int) $l['amount'];
        }
    }

    $totalExpense = 0;
    foreach ($expenses as $e) {
        $totalExpense += (int) $e['amount'];
    }

    return [
        'summary' => [
            'cash_in' => $cashIn,
            'cash_out' => $cashOut,
            'net_cash_flow' => $cashIn - $cashOut,
            'total_expense' => $totalExpense,
        ],
        'categories' => [
            'Operasional',
            'Bahan Baku',
            'Transportasi',
            'Kebersihan',
            'Perlengkapan',
            'Lainnya',
        ],
        'outlets' => [
            'Outlet Utama',
            'Outlet Cabang Barat',
        ],
        'ledgers' => $ledgers,
        'expenses' => $expenses,
    ];
};
