<?php

return function (): array {
    if (! app()->environment('local', 'testing')) {
        return [
            'summary' => [
                'total_products' => 0,
                'total_services' => 0,
                'active_categories' => 0,
                'active_items' => 0,
            ],
            'categories' => [],
            'products' => [],
            'services' => [],
        ];
    }

    return [
        'summary' => [
            'total_products' => 8,
            'total_services' => 3,
            'active_categories' => 4,
            'active_items' => 10,
        ],
        'categories' => [
            [
                'id' => 1,
                'name' => 'Minuman',
                'status' => 'active',
                'items_count' => 4,
            ],
            [
                'id' => 2,
                'name' => 'Makanan',
                'status' => 'active',
                'items_count' => 3,
            ],
            [
                'id' => 3,
                'name' => 'Bahan Baku',
                'status' => 'active',
                'items_count' => 2,
            ],
            [
                'id' => 4,
                'name' => 'Layanan Laundry',
                'status' => 'active',
                'items_count' => 3,
            ],
        ],
        'products' => [
            [
                'id' => 1,
                'name' => 'Kopi Susu Gula Aren',
                'sku' => 'KOPI-001',
                'barcode' => '8991000012345',
                'category_name' => 'Minuman',
                'cost' => '11500.00',
                'price' => 25000,
                'stock' => '18.000',
                'unit' => 'cup',
                'min_stock' => '5.000',
                'status' => 'active',
                'kind' => 'product',
            ],
            [
                'id' => 2,
                'name' => 'Americano Dingin',
                'sku' => 'KOPI-002',
                'barcode' => '8991000012346',
                'category_name' => 'Minuman',
                'cost' => '8000.00',
                'price' => 22000,
                'stock' => '3.000',
                'unit' => 'cup',
                'min_stock' => '5.000',
                'status' => 'active',
                'kind' => 'product',
            ],
            [
                'id' => 3,
                'name' => 'Caramel Macchiato',
                'sku' => 'KOPI-003',
                'barcode' => null,
                'category_name' => 'Minuman',
                'cost' => '15000.00',
                'price' => 38000,
                'stock' => '0.000',
                'unit' => 'cup',
                'min_stock' => '5.000',
                'status' => 'active',
                'kind' => 'product',
            ],
            [
                'id' => 4,
                'name' => 'Cup 16oz',
                'sku' => 'PKG-001',
                'barcode' => '8991000099901',
                'category_name' => 'Bahan Baku',
                'cost' => '450.00',
                'price' => 1000,
                'stock' => '-2.000',
                'unit' => 'pcs',
                'min_stock' => '20.000',
                'status' => 'active',
                'kind' => 'product',
            ],
            [
                'id' => 5,
                'name' => 'Croissant Almond',
                'sku' => 'PAS-001',
                'barcode' => '8991000033301',
                'category_name' => 'Makanan',
                'cost' => '14000.00',
                'price' => 28000,
                'stock' => '12.000',
                'unit' => 'pcs',
                'min_stock' => '4.000',
                'status' => 'active',
                'kind' => 'product',
            ],
            [
                'id' => 6,
                'name' => 'Cinnamon Roll',
                'sku' => 'PAS-002',
                'barcode' => null,
                'category_name' => 'Makanan',
                'cost' => '12000.00',
                'price' => 23000,
                'stock' => '2.000',
                'unit' => 'pcs',
                'min_stock' => '4.000',
                'status' => 'active',
                'kind' => 'product',
            ],
            [
                'id' => 7,
                'name' => 'Pasta Carbonara',
                'sku' => 'FOD-002',
                'barcode' => null,
                'category_name' => 'Makanan',
                'cost' => '28000.00',
                'price' => 59000,
                'stock' => '8.000',
                'unit' => 'porsi',
                'min_stock' => '3.000',
                'status' => 'active',
                'kind' => 'product',
            ],
            [
                'id' => 8,
                'name' => 'Biji Kopi Arabika 250g',
                'sku' => 'RAW-001',
                'barcode' => '8991000077701',
                'category_name' => 'Bahan Baku',
                'cost' => '45000.00',
                'price' => 85000,
                'stock' => '4.250',
                'unit' => 'kg',
                'min_stock' => '2.000',
                'status' => 'inactive',
                'kind' => 'product',
            ],
        ],
        'services' => [
            [
                'id' => 101,
                'name' => 'Laundry Kiloan',
                'sku' => 'LND-001',
                'category_name' => 'Layanan Laundry',
                'price' => 8000,
                'pricing_unit' => 'per_kg',
                'min_quantity' => '1.000',
                'unit' => 'kg',
                'estimated_duration' => '2 hari',
                'status' => 'active',
                'kind' => 'service',
            ],
            [
                'id' => 102,
                'name' => 'Cuci Bedcover',
                'sku' => 'LND-002',
                'category_name' => 'Layanan Laundry',
                'price' => 35000,
                'pricing_unit' => 'per_unit',
                'min_quantity' => '1.000',
                'unit' => 'pcs',
                'estimated_duration' => '3 hari',
                'status' => 'active',
                'kind' => 'service',
            ],
            [
                'id' => 103,
                'name' => 'Jasa Antar Jemput',
                'sku' => 'SRV-001',
                'category_name' => 'Layanan Laundry',
                'price' => 15000,
                'pricing_unit' => 'per_unit',
                'min_quantity' => '1.000',
                'unit' => 'trip',
                'estimated_duration' => '1 hari',
                'status' => 'active',
                'kind' => 'service',
            ],
        ],
    ];
};
