<?php

return function (): array {
    if (! app()->environment('local', 'testing')) {
        return [
            'summary' => [
                'total_products' => 0,
                'total_services' => 0,
                'active_categories' => 0,
                'active_items' => 0,
            ],
            'categories' => [],
            'products' => [],
            'services' => [],
        ];
    }

    $categories = [
        [
            'id' => 1,
            'name' => 'Minuman',
            'status' => 'active',
            'items_count' => 3,
        ],
        [
            'id' => 2,
            'name' => 'Makanan',
            'status' => 'active',
            'items_count' => 3,
        ],
        [
            'id' => 3,
            'name' => 'Bahan Baku',
            'status' => 'active',
            'items_count' => 2,
        ],
        [
            'id' => 4,
            'name' => 'Layanan Event',
            'status' => 'active',
            'items_count' => 3,
        ],
    ];

    $products = [
        [
            'id' => 1,
            'name' => 'Kopi Susu Gula Aren',
            'sku' => 'KOPI-001',
            'barcode' => '8991000012345',
            'category_name' => 'Minuman',
            'cost' => '11500.00',
            'price' => 25000,
            'stock' => '18.000',
            'unit' => 'cup',
            'min_stock' => '5.000',
            'status' => 'active',
            'kind' => 'product',
        ],
        [
            'id' => 2,
            'name' => 'Americano Dingin',
            'sku' => 'KOPI-002',
            'barcode' => '8991000012346',
            'category_name' => 'Minuman',
            'cost' => '8000.00',
            'price' => 22000,
            'stock' => '3.000',
            'unit' => 'cup',
            'min_stock' => '5.000',
            'status' => 'active',
            'kind' => 'product',
        ],
        [
            'id' => 3,
            'name' => 'Caramel Macchiato',
            'sku' => 'KOPI-003',
            'barcode' => null,
            'category_name' => 'Minuman',
            'cost' => '15000.00',
            'price' => 38000,
            'stock' => '0.000',
            'unit' => 'cup',
            'min_stock' => '5.000',
            'status' => 'active',
            'kind' => 'product',
        ],
        [
            'id' => 4,
            'name' => 'Cup 16oz',
            'sku' => 'PKG-001',
            'barcode' => '8991000099901',
            'category_name' => 'Bahan Baku',
            'cost' => '450.00',
            'price' => 1000,
            'stock' => '-2.000',
            'unit' => 'pcs',
            'min_stock' => '20.000',
            'status' => 'active',
            'kind' => 'product',
        ],
        [
            'id' => 5,
            'name' => 'Croissant Almond',
            'sku' => 'PAS-001',
            'barcode' => '8991000033301',
            'category_name' => 'Makanan',
            'cost' => '14000.00',
            'price' => 28000,
            'stock' => '12.000',
            'unit' => 'pcs',
            'min_stock' => '4.000',
            'status' => 'active',
            'kind' => 'product',
        ],
        [
            'id' => 6,
            'name' => 'Cinnamon Roll',
            'sku' => 'PAS-002',
            'barcode' => null,
            'category_name' => 'Makanan',
            'cost' => '12000.00',
            'price' => 23000,
            'stock' => '2.000',
            'unit' => 'pcs',
            'min_stock' => '4.000',
            'status' => 'active',
            'kind' => 'product',
        ],
        [
            'id' => 7,
            'name' => 'Pasta Carbonara',
            'sku' => 'FOD-002',
            'barcode' => null,
            'category_name' => 'Makanan',
            'cost' => '28000.00',
            'price' => 59000,
            'stock' => '8.000',
            'unit' => 'porsi',
            'min_stock' => '3.000',
            'status' => 'active',
            'kind' => 'product',
        ],
        [
            'id' => 8,
            'name' => 'Biji Kopi Arabika 250g',
            'sku' => 'RAW-001',
            'barcode' => '8991000077701',
            'category_name' => 'Bahan Baku',
            'cost' => '45000.00',
            'price' => 85000,
            'stock' => '4.250',
            'unit' => 'kg',
            'min_stock' => '2.000',
            'status' => 'inactive',
            'kind' => 'product',
        ],
    ];

    $services = [
        [
            'id' => 101,
            'name' => 'Paket Coffee Break',
            'sku' => 'SRV-001',
            'category_name' => 'Layanan Event',
            'price' => 45000,
            'pricing_unit' => 'paket',
            'min_quantity' => '10.000',
            'unit' => 'paket',
            'estimated_duration' => '3 jam',
            'status' => 'active',
            'kind' => 'service',
        ],
        [
            'id' => 102,
            'name' => 'Coffee Cart Pop-up',
            'sku' => 'SRV-002',
            'category_name' => 'Layanan Event',
            'price' => 1500000,
            'pricing_unit' => 'sesi',
            'min_quantity' => '1.000',
            'unit' => 'sesi',
            'estimated_duration' => '4 jam',
            'status' => 'active',
            'kind' => 'service',
        ],
        [
            'id' => 103,
            'name' => 'Jasa Roasting Kustom',
            'sku' => 'SRV-003',
            'category_name' => 'Layanan Event',
            'price' => 75000,
            'pricing_unit' => 'kg',
            'min_quantity' => '2.000',
            'unit' => 'kg',
            'estimated_duration' => '1 hari',
            'status' => 'active',
            'kind' => 'service',
        ],
    ];

    $activeCategories = count(array_filter($categories, fn ($c) => $c['status'] === 'active'));
    $activeProducts = count(array_filter($products, fn ($p) => $p['status'] === 'active'));
    $activeServices = count(array_filter($services, fn ($s) => $s['status'] === 'active'));

    return [
        'summary' => [
            'total_products' => count($products),
            'total_services' => count($services),
            'active_categories' => $activeCategories,
            'active_items' => $activeProducts + $activeServices,
        ],
        'categories' => $categories,
        'products' => $products,
        'services' => $services,
    ];
};
